version: "5"
services:
  emailservice:
    build: .
    restart: always
    ports:
      - ${EMAIL_CONTAINER_PORT}:${EMAIL_CONTAINER_PORT}
    container_name: ${EMAIL_CONTAINER_NAME}
    networks:
      - local-diskie-net
networks:
  local-diskie-net:
    external: true

#todo add volume
