version: '3.1'

services:
  postgressDb:
    restart: always
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    build: .
    ports:
      - ${LOCAL_PORTS}:${POSTGRESSDB_PORTS}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - postgress-data:/var/lib/postgresql/data
    networks:
      -  local-diskie-net
volumes:
  postgress-data:
networks:
  local-diskie-net:
    external: true