version: "5"
services:
  gatewayapi:
    build: .
    restart: always
    ports:
      - ${APIGATEWAY_CONTAINER_PORT}:${APIGATEWAY_CONTAINER_PORT}
    container_name: ${APIGATEWAY_CONTAINER_NAME}
    networks:
      - local-diskie-net
networks:
  local-diskie-net:
    external: true

#todo add volume
