version: "5"
services:
  userservice:
    build: .
    restart: always
    container_name: ${USER_CONTAINER_NAME}
    networks:
      - local-diskie-net
networks:
  local-diskie-net:
    external: true

#todo add volume
