version: "5"
services:
  notificationservice:
    build: .
    restart: always
    container_name: ${NOTIF_CONTAINER_NAME}
    networks:
      - local-diskie-net
networks:
  local-diskie-net:
    external: true

#todo add volume
