version: "5"
services:
  livegameservice:
    build: .
    restart: always
    ports:
      - ${LIVE_CONTAINER_PORT}:${LIVE_CONTAINER_PORT}
    container_name: ${LIVE_CONTAINER_NAME}
    networks:
      - local-diskie-net
networks:
  local-diskie-net:
    external: true

#todo add volume
