version: "5"
services:
  gameservice:
    build: .
    restart: always
    ports:
      - ${GAME_CONTAINER_PORT}:${GAME_CONTAINER_PORT}
    container_name: ${GAME_CONTAINER_NAME}
    networks:
      - local-diskie-net
networks:
  local-diskie-net:
    external: true

#todo add volume
