version: '3.1'

services:
  pg-admin:
    restart: always
    image: dpage/pgadmin4:latest
    container_name: ${CONTAINER_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - ${LOCAL_PORT}:${PG_ADMIN_PORT}
    volumes:
      - pg-admin-data:/var/lib/pgadmin1
    networks:
      -  local-diskie-net
networks:
  local-diskie-net:
    external: true
volumes:
  pg-admin-data:
