version: "5"
services:
  configserver:
    build: .
    restart: always
    ports:
      - ${CONFIG_CONTAINER_PORT}:${CONFIG_CONTAINER_PORT}
    container_name: ${CONFIG_CONTAINER_NAME}
    networks:
      - local-diskie-net
networks:
  local-diskie-net:
    external: true

#todo add volume
