version: "5"
services:
  localdiskie:
    image: mongo:latest
    container_name: local-diskie-db
    ports:
      - 27017:27017
    networks:
      - local-diskie-net
    volumes:
      - mongo-data:/data/db
networks:
  local-diskie-net:
    external: true
volumes:
  mongo-data:
    driver: local