version: "5"
services:
  discoveryserver:
    build: .
    restart: always
    ports:
      - ${DISCOVER_CONTAINER_PORT}:${DISCOVER_CONTAINER_PORT}
    container_name: ${DISCOVER_CONTAINER_NAME}
    networks:
      - local-diskie-net
networks:
  local-diskie-net:
    external: true

#todo add volume
